apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: sopes1-p2
spec:
  type: ClusterIP
  selector:
    kubevirt.io/domain: grafana-vm
  ports:
    - name: grafana
      port: 3000
      targetPort: 3000
    - name: prometheus
      port: 9090
      targetPort: 9090