apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: grafana-vm
  namespace: sopes1-p2
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: grafana-vm
        app: grafana-vm
    spec:
      nodeSelector:
        nested-virtualization: enabled
      tolerations:
        - key: kubevirt.io/dedicated
          operator: Equal
          value: virtualization
          effect: NoSchedule
      domain:
        cpu:
          cores: 1
        resources:
          requests:
            memory: 2Gi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: containerddisk
              disk:
                bus: virtio
            - name: grafanadata
              disk:
                bus: virtio
            - name: prometheusdata
              disk:
                bus: virtio
            - name: cloudinit
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          containerDisk:
            image: zot.35-226-224-23.sslip.io/library/ubuntu-container-disk:24.04
            imagePullPolicy: IfNotPresent
        - name: containerddisk
          emptyDisk:
            capacity: 8Gi
        - name: grafanadata
          persistentVolumeClaim:
            claimName: grafana-data
        - name: prometheusdata
          persistentVolumeClaim:
            claimName: prometheus-data
        - name: cloudinit
          cloudInitNoCloud:
            secretRef:
              name: grafana-cloudinit