apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rabbitmq/cluster.yaml
  - go-d2/deployment.yaml
  - go-d2/service.yaml
  - go-d1/deployment.yaml
  - go-d1/service.yaml
  - rust-api/deployment.yaml
  - rust-api/service.yaml
  - gateway/gateway.yaml
  - valkey/pvc.yaml
  - valkey/vm.yaml
  - valkey/service.yaml
  - consumer/deployment.yaml
