syntax = "proto3";

package worldcup2026;

option go_package = "github.com/ipatzantzic19/202308204_LAB_SO1_VacJun2026/PROYECTO2/proto";

message MatchPredictionRequest {
  Teams  home_team  = 1;
  Teams  away_team  = 2;
  int32  home_goals = 3;
  int32  away_goals = 4;
  string username   = 5;
  string timestamp  = 6;
}

enum Teams {
  TEAMS_UNKNOWN = 0;
  GTM = 1;
  MEX = 2;
  BRA = 3;
  ARG = 4;
  ESP = 5;
}

message MatchPredictionResponse {
  string status = 1;
}

service MatchPredictionService {
  rpc SendPrediction (MatchPredictionRequest) returns (MatchPredictionResponse);
}
